Support for amphora provider services
openstack-k8s-operators/octavia-operator pull request #173
Opened 2023-09-19 18:50 UTC by beagles

Adds support for launching the amphora controller
services. Implementation is informed by the fact that the amphora provider specific services share many common configurations and deployment requirements.

Note: full deployment support isn't available with this change and would require several manual steps to enable.

2023-09-19 19:31 UTC, beagles commented
/test all

2023-09-19 19:41 UTC, beagles commented
/test all

2023-09-19 19:57 UTC, beagles commented
/test all

2023-09-20 06:57 UTC, weinimo requested changes
I found a couple of things while looking at the code. I didn't test it yet.

2023-09-20 06:57 UTC, weinimo commented on api/v1beta1/amphoracontroller_types.go
> +    ServiceAccount string `json:"serviceAccount"`
Indentation. Probably a tab vs. space issue?

2023-09-20 06:57 UTC, weinimo commented on config/manager/kustomization.yaml
> +  newName: quay.io/beagles/octavia-operator
I guess this was added accidentally.

2023-09-20 12:59 UTC, beagles commented on config/manager/kustomization.yaml
> +  newName: quay.io/beagles/octavia-operator
yup, will fix

2023-09-20 15:17 UTC, beagles commented
Seems to be having a problem getting the transporturl from rabbit, investigating

2023-09-20 18:03 UTC, beagles commented
/retest

2023-09-22 11:46 UTC, luis5tb commented
what about the driver-agent component? is that missed? or part of a follow up?

2023-09-22 11:53 UTC, beagles commented
> what about the driver-agent component? is that missed? or part of a follow up?

The driver agent is deployed along with the API in a single pod so is already there. The API service and the driver agent are inextricably linked by a socket and are 1:1 relationship so it just made more sense to collocate them in the same pod.

2023-09-22 11:54 UTC, luis5tb commented
> > what about the driver-agent component? is that missed? or part of a follow up?
> 
> The driver agent is deployed along with the API in a single pod so is already there. The API service and the driver agent are inextricably linked by a socket and are 1:1 relationship so it just made more sense to collocate them in the same pod.

awesome! thanks!

2023-09-22 14:04 UTC, dprince approved these changes

2023-09-22 14:07 UTC, merged