Revert controller update
openstack-k8s-operators/octavia-operator pull request #247
Opened 2024-02-21 16:57 UTC by weinimo

... till we found a fix for the open issues with Mariadb and kuttl.

2024-02-21 16:59 UTC, weinimo commented
/test all

2024-02-26 12:53 UTC, beagles requested changes
not sure that we need this atm

2024-02-26 12:59 UTC, abays commented
> not sure that we need this atm

I think that's right, given that https://github.com/openstack-k8s-operators/octavia-operator/pull/248 stabilized things

2024-03-04 09:30 UTC, weinimo commented
not needed

2024-03-04 09:30 UTC, closed without merging