Predictable ips
openstack-k8s-operators/octavia-operator pull request #303
Opened 2024-05-09 20:17 UTC by beagles

2024-05-10 12:10 UTC, beagles commented
/test all

2024-05-10 12:11 UTC, beagles commented on hack/configure_local_webhook.sh
> +#sudo firewall-cmd --runtime-to-permanent
Spotted... will update shortly to remove hack.

2024-06-12 01:40 UTC, beagles commented
I still have some testing to do but this is ready for review

2024-06-12 10:01 UTC, weinimo requested changes

2024-06-12 12:03 UTC, beagles commented on pkg/octavia/lb_mgmt_network.go
> +
Agreed.

2024-06-12 12:04 UTC, beagles commented on pkg/octavia/lb_mgmt_network.go
> +func GetNextIP(predParams *NADIpam, currentValues map[string]bool) (string, error) {
Agreed.

2024-06-12 12:05 UTC, beagles commented on templates/octaviaamphoracontroller/bin/setipalias.py
> +if nodefile:
Also agreed. I'm amending the script to error out also if the conditions are not met. With predictable IPs these alias IPs are now essential.

2024-06-12 17:04 UTC, gthiemonge commented
/lgtm

2024-06-12 17:09 UTC, merged